apiVersion: v1
kind: Service
metadata:
  name: python-log-reader
  labels:
    app: python-log-reader
  namespace: techtrek
spec:
  selector:
    app: python-log-reader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
