name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t python-log-reader .

    - name: Run Docker container
      run: |
        docker run --name test_container -d --memory="4g" python-log-reader
        # Replace with your actual test commands if needed

    # - name: Run unittest tests
    #   run: |
    #     docker exec test_container python -m unittest discover -s tests

    - name: Stop and remove container
      run: |
        docker stop test_container
        docker rm test_container
  
  push-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: /
        docker tag python-log-reader ghcr.io/meghe/python-log-reader:latest
        docker push ghcr.io/meghe/python-log-reader:latest